[package]
name = "cosmo_svg_animation_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.8", features = ["csr"] }
leptos-use = { version = "0.16.2", features = ["use_timestamp"] }
